spring:
  application:
    name: dev
  main:
    web-application-type: servlet

# 여기는 spring 밖(최상위)
app:
  fastapi:
    base-url: http://localhost:8000
    connect-timeout-ms: 4000
    read-timeout-ms: 30000
