spring:
  application:
    name: dev
  main:
    web-application-type: servlet
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true
  sql:
    init:
      mode: always        # 항상 SQL 파일 실행 (필수)
  jpa:
    defer-datasource-initialization: true # Hibernate가 테이블 만든 후 데이터 넣기 (중요)
    hibernate:
      ddl-auto: create-drop  # 혹은 update (개발 중엔 create-drop 추천)

# 여기는 spring 밖(최상위)
app:
  fastapi:
    base-url: http://localhost:8000
    connect-timeout-ms: 4000
    read-timeout-ms: 30000
  jwt:
    secret: "test-secret-key-12345678901234567890"
    expiry-minutes: 60

